// Add a URL only for projects that should show a website button. Leave empty for the others.
const projectLinks={sonatrach:"",automotive:"",pfe:""};

const details={
huawei:{
 label:{en:"2026 · SHENZHEN, CHINA",fr:"2026 · SHENZHEN, CHINE",ar:"2026 · شنتشن، الصين",de:"2026 · SHENZHEN, CHINA",es:"2026 · SHENZHEN, CHINA"},
 title:{en:"Huawei ICT Competition — Global Grand Prize",fr:"Huawei ICT Competition — Grand Prix mondial",ar:"مسابقة Huawei ICT — الجائزة الكبرى العالمية",de:"Huawei ICT Competition — Globaler Hauptpreis",es:"Huawei ICT Competition — Gran Premio Mundial"},
 body:{en:"Nesrine and her team achieved the Global Grand Prize at the Huawei ICT Competition international final in Shenzhen, China, in June 2026. Nesrine worked primarily on the AI side of the challenge, which involved time-series based computer-failure prediction under a constrained, no-AI/LLM working environment. The broader team also handled cloud-side components including microservices and firewall infrastructure.",fr:"Nesrine et son équipe ont remporté le Grand Prix mondial lors de la finale internationale de la Huawei ICT Competition à Shenzhen, en Chine, en juin 2026. Nesrine a principalement travaillé sur le volet IA du défi, consacré à la prédiction de pannes informatiques à partir de séries temporelles dans un environnement contraint sans IA/LLM. L'équipe a également pris en charge des composants cloud, notamment des microservices et une infrastructure de pare-feu.",ar:"حققت نسرين وفريقها الجائزة الكبرى العالمية في النهائي الدولي لمسابقة Huawei ICT في شنتشن، الصين، في يونيو 2026. عملت نسرين بشكل أساسي على جانب الذكاء الاصطناعي من التحدي، الذي تضمن التنبؤ بأعطال الحواسيب اعتمادًا على السلاسل الزمنية ضمن بيئة عمل مقيدة ومن دون استخدام الذكاء الاصطناعي أو نماذج اللغة الكبيرة. كما تولى الفريق مكونات سحابية شملت الخدمات المصغرة والبنية التحتية لجدار الحماية.",de:"Nesrine und ihr Team erreichten beim internationalen Finale der Huawei ICT Competition im Juni 2026 in Shenzhen, China, den Globalen Hauptpreis. Nesrine arbeitete hauptsächlich am KI-Teil der Aufgabe, bei dem Computerausfälle anhand von Zeitreihendaten in einer eingeschränkten Umgebung ohne KI/LLM vorhergesagt wurden. Das Team übernahm außerdem Cloud-Komponenten wie Microservices und Firewall-Infrastruktur.",es:"Nesrine y su equipo lograron el Gran Premio Mundial en la final internacional de la Huawei ICT Competition en Shenzhen, China, en junio de 2026. Nesrine trabajó principalmente en la parte de IA del reto, que consistía en predecir fallos informáticos a partir de series temporales en un entorno restringido sin IA/LLM. El equipo también trabajó en componentes cloud, incluidos microservicios e infraestructura de firewall."},
 tags:{en:["Global Grand Prize","Artificial Intelligence","Time Series","Huawei","Shenzhen"],fr:["Grand Prix mondial","Intelligence artificielle","Séries temporelles","Huawei","Shenzhen"],ar:["الجائزة الكبرى العالمية","الذكاء الاصطناعي","السلاسل الزمنية","Huawei","شنتشن"],de:["Globaler Hauptpreis","Künstliche Intelligenz","Zeitreihen","Huawei","Shenzhen"],es:["Gran Premio Mundial","Inteligencia Artificial","Series temporales","Huawei","Shenzhen"]},
 gallery:{en:["Team photo","Competition stage","Global final","Prize ceremony","Shenzhen","Behind the scenes"],fr:["Photo de l'équipe","Scène de compétition","Finale mondiale","Cérémonie de remise du prix","Shenzhen","Coulisses"],ar:["صورة الفريق","منصة المسابقة","النهائي العالمي","حفل تسليم الجائزة","شنتشن","خلف الكواليس"],de:["Teamfoto","Wettbewerbsbühne","Weltfinale","Preisverleihung","Shenzhen","Hinter den Kulissen"],es:["Foto del equipo","Escenario de competición","Final mundial","Ceremonia de premios","Shenzhen","Entre bastidores"]}
},
seeds:{
 label:{en:"INTERNATIONAL EXPERIENCE · CHINA",fr:"EXPÉRIENCE INTERNATIONALE · CHINE",ar:"تجربة دولية · الصين",de:"INTERNATIONALE ERFAHRUNG · CHINA",es:"EXPERIENCIA INTERNACIONAL · CHINA"},
 title:{en:"Huawei Seeds for the Future",fr:"Huawei Seeds for the Future",ar:"برنامج Huawei Seeds for the Future",de:"Huawei Seeds for the Future",es:"Huawei Seeds for the Future"},
 body:{en:"Nesrine represented Algeria in Huawei Seeds for the Future in Shenzhen, China. The program exposed her to Huawei technologies and topics including AI, 5G/6G, cloud, innovation and entrepreneurship, while giving her an international collaborative experience.",fr:"Nesrine a représenté l'Algérie dans le programme Huawei Seeds for the Future à Shenzhen, en Chine. Le programme lui a permis de découvrir les technologies Huawei et des thèmes tels que l'IA, la 5G/6G, le cloud, l'innovation et l'entrepreneuriat, tout en lui offrant une expérience internationale et collaborative.",ar:"مثلت نسرين الجزائر في برنامج Huawei Seeds for the Future في شنتشن، الصين. أتاح لها البرنامج التعرف على تقنيات Huawei ومواضيع تشمل الذكاء الاصطناعي و5G/6G والحوسبة السحابية والابتكار وريادة الأعمال، إلى جانب تجربة دولية وتعاونية.",de:"Nesrine vertrat Algerien bei Huawei Seeds for the Future in Shenzhen, China. Das Programm vermittelte Einblicke in Huawei-Technologien sowie in KI, 5G/6G, Cloud, Innovation und Unternehmertum und bot internationale Zusammenarbeit.",es:"Nesrine representó a Argelia en Huawei Seeds for the Future en Shenzhen, China. El programa le permitió conocer tecnologías de Huawei y temas como IA, 5G/6G, cloud, innovación y emprendimiento, además de ofrecerle una experiencia internacional y colaborativa."},
 tags:{en:["China","Huawei","5G","6G","AI","Innovation"],fr:["Chine","Huawei","5G","6G","IA","Innovation"],ar:["الصين","Huawei","5G","6G","الذكاء الاصطناعي","الابتكار"],de:["China","Huawei","5G","6G","KI","Innovation"],es:["China","Huawei","5G","6G","IA","Innovación"]},
 gallery:{en:["Shenzhen","Program moments","Huawei technology","Team","Cultural experience","Final day"],fr:["Shenzhen","Moments du programme","Technologie Huawei","Équipe","Expérience culturelle","Dernier jour"],ar:["شنتشن","لحظات من البرنامج","تقنيات Huawei","الفريق","التجربة الثقافية","اليوم الأخير"],de:["Shenzhen","Programmmomente","Huawei-Technologie","Team","Kulturelle Erfahrung","Letzter Tag"],es:["Shenzhen","Momentos del programa","Tecnología Huawei","Equipo","Experiencia cultural","Último día"]}
},
craag:{
 label:{en:"RESEARCH EXPERIENCE · ALGERIA",fr:"EXPÉRIENCE DE RECHERCHE · ALGÉRIE",ar:"تجربة بحثية · الجزائر",de:"FORSCHUNGSERFAHRUNG · ALGERIEN",es:"EXPERIENCIA DE INVESTIGACIÓN · ARGELIA"},
 title:{en:"AI Research Internship — CRAAG",fr:"Stage de recherche en IA — CRAAG",ar:"تدريب بحثي في الذكاء الاصطناعي — CRAAG",de:"KI-Forschungspraktikum — CRAAG",es:"Prácticas de investigación en IA — CRAAG"},
 body:{en:"Nesrine completed an AI Research Internship at the Research Center in Astronomy, Astrophysics and Geophysics (CRAAG). The experience forms an important part of her research-oriented profile.",fr:"Nesrine a effectué un stage de recherche en IA au Centre de Recherche en Astronomie, Astrophysique et Géophysique (CRAAG). Cette expérience constitue une partie importante de son profil orienté vers la recherche.",ar:"أكملت نسرين تدريبًا بحثيًا في الذكاء الاصطناعي لدى مركز البحث في علم الفلك والفيزياء الفلكية والجيوفيزياء (CRAAG). وتمثل هذه التجربة جزءًا مهمًا من مسارها البحثي.",de:"Nesrine absolvierte ein Forschungspraktikum im Bereich KI am Forschungszentrum für Astronomie, Astrophysik und Geophysik (CRAAG). Diese Erfahrung ist ein wichtiger Bestandteil ihres forschungsorientierten Profils.",es:"Nesrine realizó unas prácticas de investigación en IA en el Centro de Investigación de Astronomía, Astrofísica y Geofísica (CRAAG). Esta experiencia constituye una parte importante de su perfil orientado a la investigación."},
 tags:{en:["Research","Artificial Intelligence","CRAAG"],fr:["Recherche","Intelligence artificielle","CRAAG"],ar:["البحث","الذكاء الاصطناعي","CRAAG"],de:["Forschung","Künstliche Intelligenz","CRAAG"],es:["Investigación","Inteligencia Artificial","CRAAG"]},
 gallery:{en:["Research environment","Project","Team","Presentation"],fr:["Environnement de recherche","Projet","Équipe","Présentation"],ar:["بيئة البحث","المشروع","الفريق","العرض"],de:["Forschungsumgebung","Projekt","Team","Präsentation"],es:["Entorno de investigación","Proyecto","Equipo","Presentación"]}
},
academic:{
 label:{en:"ACADEMIC EXCELLENCE",fr:"EXCELLENCE ACADÉMIQUE",ar:"التميز الأكاديمي",de:"AKADEMISCHE EXZELLENZ",es:"EXCELENCIA ACADÉMICA"},
 title:{en:"Academic & National Recognition",fr:"Reconnaissance académique et nationale",ar:"التكريم الأكاديمي والوطني",de:"Akademische und nationale Anerkennung",es:"Reconocimiento académico y nacional"},
 body:{en:"Nesrine has ranked 1st in her ENSIA promotion for the past four years. She obtained 18.91/20 in the Mathematics Baccalauréat and ranked 3rd nationally. She has also received national presidential recognition connected to her academic performance and achievements, including recognition in March 2025.",fr:"Nesrine s'est classée 1ère de sa promotion à l'ENSIA pendant les quatre dernières années. Elle a obtenu 18,91/20 au baccalauréat de mathématiques et s'est classée 3e au niveau national. Elle a également reçu une reconnaissance présidentielle nationale liée à ses performances et réalisations académiques, notamment en mars 2025.",ar:"احتلت نسرين المرتبة الأولى في دفعتها في ENSIA خلال السنوات الأربع الماضية. حصلت على 18.91/20 في بكالوريا الرياضيات واحتلت المرتبة الثالثة وطنيًا. كما حظيت بتكريم رئاسي وطني مرتبط بأدائها وإنجازاتها الأكاديمية، بما في ذلك تكريم في مارس 2025.",de:"Nesrine belegte in den vergangenen vier Jahren den ersten Platz ihres ENSIA-Jahrgangs. Im Mathematik-Baccalauréat erzielte sie 18,91/20 und belegte landesweit den dritten Platz. Außerdem erhielt sie eine nationale Anerkennung auf Präsidentenebene im Zusammenhang mit ihren akademischen Leistungen, unter anderem im März 2025.",es:"Nesrine ha ocupado el primer puesto de su promoción en ENSIA durante los últimos cuatro años. Obtuvo 18,91/20 en el Bachillerato de Matemáticas y quedó 3.ª a nivel nacional. También recibió un reconocimiento presidencial nacional relacionado con su rendimiento y logros académicos, incluido un reconocimiento en marzo de 2025."},
 tags:{en:["ENSIA","18.91/20","3rd nationally","National recognition"],fr:["ENSIA","18,91/20","3e au niveau national","Reconnaissance nationale"],ar:["ENSIA","18.91/20","المرتبة الثالثة وطنيًا","تكريم وطني"],de:["ENSIA","18,91/20","Platz 3 landesweit","Nationale Anerkennung"],es:["ENSIA","18,91/20","3.ª a nivel nacional","Reconocimiento nacional"]},
 gallery:{en:["Recognition","ENSIA","Academic milestone","Ceremony"],fr:["Reconnaissance","ENSIA","Étape académique","Cérémonie"],ar:["التكريم","ENSIA","محطة أكاديمية","الحفل"],de:["Anerkennung","ENSIA","Akademischer Meilenstein","Zeremonie"],es:["Reconocimiento","ENSIA","Hito académico","Ceremonia"]}
},
sonatrach:{
 label:{en:"AI / MACHINE LEARNING PROJECT",fr:"PROJET IA / APPRENTISSAGE AUTOMATIQUE",ar:"مشروع ذكاء اصطناعي / تعلم آلي",de:"KI-/MACHINE-LEARNING-PROJEKT",es:"PROYECTO DE IA / APRENDIZAJE AUTOMÁTICO"},
 title:{en:"Sonatrach Lithology Prediction",fr:"Prédiction de la lithologie pour Sonatrach",ar:"التنبؤ بالليثولوجيا لصالح سوناطراك",de:"Lithologie-Vorhersage für Sonatrach",es:"Predicción de litología para Sonatrach"},
 body:{en:"An academic AI project applying machine learning to petroleum and geological data for lithology prediction, including data such as gamma-ray measurements. Detailed methodology, metrics and project links can be added to this page as the portfolio content is finalized.",fr:"Un projet académique en IA appliquant l'apprentissage automatique à des données pétrolières et géologiques pour la prédiction de la lithologie, notamment des mesures de rayons gamma. La méthodologie détaillée, les métriques et les liens du projet pourront être ajoutés lorsque le contenu du portfolio sera finalisé.",ar:"مشروع أكاديمي في الذكاء الاصطناعي يطبق التعلم الآلي على بيانات بترولية وجيولوجية للتنبؤ بالليثولوجيا، بما في ذلك بيانات مثل قياسات أشعة غاما. يمكن إضافة المنهجية التفصيلية والمقاييس وروابط المشروع عند استكمال محتوى الموقع.",de:"Ein akademisches KI-Projekt, das maschinelles Lernen auf Erdöl- und Geologiedaten zur Lithologie-Vorhersage anwendet, einschließlich Daten wie Gamma-Ray-Messungen. Detaillierte Methodik, Kennzahlen und Projektlinks können ergänzt werden, sobald der Portfolioinhalt finalisiert ist.",es:"Proyecto académico de IA que aplica aprendizaje automático a datos petroleros y geológicos para predecir la litología, incluidos datos como mediciones de rayos gamma. La metodología detallada, las métricas y los enlaces del proyecto podrán añadirse cuando se finalice el contenido del portafolio."},
 tags:{en:["Machine Learning","Python","Geoscience","Petroleum"],fr:["Apprentissage automatique","Python","Géosciences","Pétrole"],ar:["التعلم الآلي","Python","علوم الأرض","البترول"],de:["Maschinelles Lernen","Python","Geowissenschaften","Erdöl"],es:["Aprendizaje automático","Python","Geociencias","Petróleo"]}
},
automotive:{
 label:{en:"AI PLATFORM · CONCEPT / DEVELOPMENT",fr:"PLATEFORME IA · CONCEPT / DÉVELOPPEMENT",ar:"منصة ذكاء اصطناعي · مفهوم / تطوير",de:"KI-PLATTFORM · KONZEPT / ENTWICKLUNG",es:"PLATAFORMA DE IA · CONCEPTO / DESARROLLO"},
 title:{en:"AI Automotive Spare-Parts Platform",fr:"Plateforme IA de pièces automobiles",ar:"منصة ذكاء اصطناعي لقطع غيار السيارات",de:"KI-Plattform für Kfz-Ersatzteile",es:"Plataforma de IA para repuestos de automoción"},
 body:{en:"A proposed intelligent automotive spare-parts platform combining AI search, OEM and vehicle-reference lookup, stock and price comparison, supplier comparison, ordering, invoice upload, role-based workflows, multilingual interfaces, RAG, decision memory and workflow automation with n8n and Docker. This entry is intentionally presented as a project concept/development effort rather than a finished production product.",fr:"Une plateforme intelligente proposée pour les pièces automobiles, combinant recherche IA, recherche par référence OEM et véhicule, comparaison des stocks et des prix, comparaison des fournisseurs, commandes, téléchargement de factures, workflows par rôle, interfaces multilingues, RAG, mémoire décisionnelle et automatisation avec n8n et Docker. Cette entrée est présentée comme un concept/projet en développement, et non comme un produit de production terminé.",ar:"منصة ذكية مقترحة لقطع غيار السيارات تجمع بين البحث بالذكاء الاصطناعي، والبحث حسب مرجع OEM والمركبة، ومقارنة المخزون والأسعار والموردين، والطلبات، ورفع الفواتير، وسير العمل حسب الأدوار، والواجهات متعددة اللغات، وRAG، وذاكرة القرارات، وأتمتة سير العمل باستخدام n8n وDocker. ويُعرض هذا المشروع كمفهوم/جهد تطوير وليس كمنتج نهائي جاهز للإنتاج.",de:"Eine geplante intelligente Plattform für Kfz-Ersatzteile mit KI-Suche, Suche nach OEM- und Fahrzeugreferenzen, Bestands- und Preisvergleich, Lieferantenvergleich, Bestellungen, Rechnungsupload, rollenbasierten Workflows, mehrsprachigen Oberflächen, RAG, Entscheidungs- und Workflow-Automatisierung mit n8n und Docker. Der Eintrag wird bewusst als Konzept/Entwicklungsprojekt und nicht als fertiges Produktionsprodukt dargestellt.",es:"Una plataforma inteligente propuesta para repuestos de automoción que combina búsqueda con IA, consulta por referencia OEM y vehículo, comparación de stock y precios, comparación de proveedores, pedidos, carga de facturas, flujos por roles, interfaces multilingües, RAG, memoria de decisiones y automatización con n8n y Docker. Esta entrada se presenta intencionadamente como concepto/proyecto en desarrollo y no como producto de producción terminado."},
 tags:{en:["RAG","AI Agents","n8n","Docker","Automotive"],fr:["RAG","Agents IA","n8n","Docker","Automobile"],ar:["RAG","وكلاء الذكاء الاصطناعي","n8n","Docker","السيارات"],de:["RAG","KI-Agenten","n8n","Docker","Automotive"],es:["RAG","Agentes de IA","n8n","Docker","Automoción"]}
},
pfe:{
 label:{en:"CURRENT ACADEMIC DIRECTION",fr:"ORIENTATION ACADÉMIQUE ACTUELLE",ar:"التوجه الأكاديمي الحالي",de:"AKTUELLE AKADEMISCHE RICHTUNG",es:"DIRECCIÓN ACADÉMICA ACTUAL"},
 title:{en:"5G Integration with Augmented Reality",fr:"Intégration de la 5G avec la réalité augmentée",ar:"دمج شبكات 5G مع الواقع المعزز",de:"Integration von 5G mit Augmented Reality",es:"Integración de 5G con Realidad Aumentada"},
 body:{en:"Nesrine's current PFE direction explores the integration of 5G technologies with Augmented Reality. This is a current academic direction and should be expanded with the final research question, methodology and results once they are available.",fr:"L'orientation actuelle du PFE de Nesrine explore l'intégration des technologies 5G avec la réalité augmentée. Il s'agit d'une orientation académique en cours qui sera complétée par la question de recherche finale, la méthodologie et les résultats lorsqu'ils seront disponibles.",ar:"يتناول توجه نسرين الحالي في مشروع نهاية الدراسة دمج تقنيات 5G مع الواقع المعزز. وهذا توجه أكاديمي قيد التطوير، وسيتم توسيعه بسؤال البحث النهائي والمنهجية والنتائج عند توفرها.",de:"Nesrines aktuelle PFE-Richtung untersucht die Integration von 5G-Technologien mit Augmented Reality. Dies ist eine laufende akademische Richtung und wird um die endgültige Forschungsfrage, Methodik und Ergebnisse ergänzt, sobald diese vorliegen.",es:"La dirección actual del PFE de Nesrine explora la integración de tecnologías 5G con Realidad Aumentada. Es una línea académica en curso que se ampliará con la pregunta de investigación final, la metodología y los resultados cuando estén disponibles."},
 tags:{en:["5G","Augmented Reality","Research"],fr:["5G","Réalité augmentée","Recherche"],ar:["5G","الواقع المعزز","بحث"],de:["5G","Augmented Reality","Forschung"],es:["5G","Realidad Aumentada","Investigación"]}
}
};

function openDetail(key){window.currentDetailKey=key;
 const d=details[key], lang=localStorage.getItem("lang")||"en";
 const site=projectLinks[key]||"";
 const siteButton=site?`<a class="project-site-btn" href="${site}" target="_blank" rel="noopener" onclick="event.stopPropagation()">${T[lang]["project.visit"]}</a>`:"";
 const tags=(d.tags[lang]||d.tags.en).map(x=>`<span>${x}</span>`).join("");
 const gallery=(d.gallery?.[lang]||d.gallery?.en||["01","02","03","04"]).map((x,i)=>`<div class="gallery-slot"><div class="slot-num">${String(i+1).padStart(2,"0")}</div><span>${x}</span></div>`).join("");
 document.getElementById("modal-content").innerHTML=`<div class="label">${d.label[lang]}</div><h2>${d.title[lang]}</h2><p>${d.body[lang]}</p><div class="modal-tags">${tags}</div>${siteButton}<div class="gallery-title">${T[lang]["project.gallery"]} <small>${T[lang]["project.replace"]}</small></div><div class="gallery">${gallery}</div>`;
 document.getElementById("modal").classList.add("open");document.getElementById("modal").setAttribute("aria-hidden","false");
}
function closeDetail(){document.getElementById("modal").classList.remove("open");document.getElementById("modal").setAttribute("aria-hidden","true")}
document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeDetail()});
document.querySelector(".menu").addEventListener("click",()=>document.querySelector(".nav-links").classList.toggle("open"));
function sendMail(e){e.preventDefault();const n=encodeURIComponent(document.getElementById("name").value),em=encodeURIComponent(document.getElementById("email").value),s=encodeURIComponent(document.getElementById("subject").value),m=encodeURIComponent(document.getElementById("message").value);window.location.href=`mailto:YOUR_EMAIL_HERE@example.com?subject=${s}&body=Name:%20${n}%0AEmail:%20${em}%0A%0A${m}`;return false}
const T={
en:{
'nav.about':'About','nav.experience':'Experience','nav.projects':'Projects','nav.cv':'CV','nav.contact':'Contact','nav.download':'Download CV',
'hero.role':'AI Engineer · Researcher · Technology Enthusiast','hero.copy':'AI Engineering student at ENSIA with a strong academic record, international technology experience, and research interests spanning Artificial Intelligence, Reinforcement Learning, Agentic AI and 5G/6G systems.','hero.work':'Explore my work','hero.contact':"Let's connect",
'stats.rank':'Ranked 1st in ENSIA promotion for four consecutive years','stats.bac':'Mathematics Baccalauréat · 3rd nationally',
'about.title':'Building intelligent systems for real-world problems.','about.p1':'I am a 5th-year AI Engineering student at ENSIA, combining engineering, research and management studies. My academic journey has been shaped by a strong interest in intelligent decision-making and emerging technologies.','about.p2':'My interests include agentic AI, reinforcement learning, hierarchical decision-making, intelligent networking and AI-driven 5G/6G systems. I also enjoy turning technical ideas into practical digital products.',
'experience.label':'EXPERIENCE & ACHIEVEMENTS','experience.title':'Milestones that shaped my journey.',
'projects.eyebrow':'PROJECTS','projects.title':'Selected work.','projects.subtitle':'AI · Research · Software',
'ach.huawei.meta':'2026 · SHENZHEN, CHINA','ach.huawei.title':'Huawei ICT Competition — Global Grand Prize','ach.huawei.card':'International competition achievement with a focus on the AI side of a time-series computer-failure prediction challenge.',
'ach.seeds.meta':'INTERNATIONAL EXPERIENCE','ach.seeds.title':'Huawei Seeds for the Future','ach.seeds.card':'Represented Algeria in Shenzhen and explored Huawei technologies, 5G/6G, cloud, AI and innovation.',
'ach.craag.meta':'RESEARCH EXPERIENCE · ALGERIA','ach.craag.title':'AI Research Internship — CRAAG','ach.craag.card':'Research experience at the Research Center in Astronomy, Astrophysics and Geophysics.',
'ach.academic.meta':'ACADEMIC EXCELLENCE','ach.academic.title':'Academic & National Recognition','ach.academic.card':'1st in the ENSIA promotion for four years, 18.91/20 in Mathematics Baccalauréat, 3rd nationally, and national presidential recognition.',
'proj.sonatrach.title':'Sonatrach Lithology Prediction','proj.sonatrach.card':'Machine learning applied to petroleum and geological data for lithology prediction.',
'proj.automotive.title':'AI Automotive Spare-Parts Platform','proj.automotive.card':'Concept for an intelligent multilingual platform combining AI search, RAG, stock, suppliers and workflow automation.',
'proj.pfe.title':'5G Integration with Augmented Reality','proj.pfe.card':'Current academic direction exploring the integration of next-generation connectivity with AR.',
'common.details':'View details →','common.explore':'Explore project →',
'cv.eyebrow':'CV','cv.title':'Academic excellence.<br>Technical ambition.','cv.copy':'A concise overview of my education, research experience, international achievements and technical interests.','cv.download':'Download CV ↓','cv.edu':'EDUCATION','cv.ensia':'ENSIA · AI Engineering','cv.ensiaDesc':'5th year · Ranked 1st in promotion for four consecutive years','cv.ehec':'EHEC · Commerce & Management','cv.ehecDesc':"Master's studies alongside AI Engineering",'cv.research':'RESEARCH','cv.craag':'CRAAG · AI Research Internship','cv.craagDesc':'Research Center in Astronomy, Astrophysics and Geophysics','cv.academic':'ACADEMIC','cv.bac':'Mathematics Baccalauréat · 18.91/20','cv.bacDesc':'3rd nationally',
'contact.eyebrow':'CONTACT','contact.title':"Let's build something meaningful.",'contact.copy':'Open to research collaborations, technology opportunities, internships, projects and meaningful conversations around Artificial Intelligence and emerging technologies.',
'form.name':'Name','form.email':'Email','form.subject':'Subject','form.message':'Message','form.send':'Send message ↗','footer.role':'AI Engineer · Researcher',
'project.visit':'Visit website ↗','project.gallery':'Gallery','project.replace':'Replace these slots with your real photos'
},
fr:{
'nav.about':'À propos','nav.experience':'Expérience','nav.projects':'Projets','nav.cv':'CV','nav.contact':'Contact','nav.download':'Télécharger le CV',
'hero.role':'Ingénieure IA · Chercheuse · Passionnée de technologie','hero.copy':"Étudiante en ingénierie de l'IA à l'ENSIA, avec un excellent parcours académique, une expérience technologique internationale et des intérêts de recherche en intelligence artificielle, apprentissage par renforcement, IA agentique et systèmes 5G/6G.",'hero.work':'Voir mes travaux','hero.contact':'Me contacter',
'stats.rank':"Classée 1ère de sa promotion à l'ENSIA pendant quatre années consécutives",'stats.bac':'Baccalauréat Mathématiques · 3e au niveau national',
'about.title':'Concevoir des systèmes intelligents pour des problèmes réels.', 'about.p1':"Je suis étudiante en 5e année d'ingénierie de l'IA à l'ENSIA, avec une formation complémentaire en management à l'EHEC.",'about.p2':"Mes centres d'intérêt comprennent l'IA agentique, l'apprentissage par renforcement, la prise de décision hiérarchique, les réseaux intelligents et l'IA appliquée aux systèmes 5G/6G.",
'experience.label':'EXPÉRIENCE & RÉALISATIONS','experience.title':'Les étapes qui ont façonné mon parcours.',
'projects.eyebrow':'PROJETS','projects.title':'Travaux sélectionnés.','projects.subtitle':'IA · Recherche · Logiciel',
'ach.huawei.meta':'2026 · SHENZHEN, CHINE','ach.huawei.title':'Huawei ICT Competition — Grand Prix mondial','ach.huawei.card':"Réussite dans une compétition internationale, avec un travail axé sur le volet IA d'un défi de prédiction de pannes informatiques à partir de séries temporelles.",
'ach.seeds.meta':'EXPÉRIENCE INTERNATIONALE','ach.seeds.title':'Huawei Seeds for the Future','ach.seeds.card':"Représentation de l'Algérie à Shenzhen et découverte des technologies Huawei, de la 5G/6G, du cloud, de l'IA et de l'innovation.",
'ach.craag.meta':'EXPÉRIENCE DE RECHERCHE · ALGÉRIE','ach.craag.title':'Stage de recherche en IA — CRAAG','ach.craag.card':'Expérience de recherche au Centre de Recherche en Astronomie, Astrophysique et Géophysique.',
'ach.academic.meta':'EXCELLENCE ACADÉMIQUE','ach.academic.title':'Reconnaissance académique et nationale','ach.academic.card':'1ère de la promotion ENSIA pendant quatre ans, 18,91/20 au baccalauréat de mathématiques, 3e au niveau national et reconnaissance présidentielle nationale.',
'proj.sonatrach.title':'Prédiction de la lithologie pour Sonatrach','proj.sonatrach.card':'Application de l’apprentissage automatique à des données pétrolières et géologiques pour prédire la lithologie.',
'proj.automotive.title':'Plateforme IA de pièces automobiles','proj.automotive.card':'Concept de plateforme multilingue intelligente combinant recherche IA, RAG, stocks, fournisseurs et automatisation des workflows.',
'proj.pfe.title':'Intégration de la 5G avec la réalité augmentée','proj.pfe.card':'Orientation académique actuelle explorant l’intégration de la connectivité de nouvelle génération avec la réalité augmentée.',
'common.details':'Voir les détails →','common.explore':'Explorer le projet →',
'cv.eyebrow':'CV','cv.title':'Excellence académique.<br>Ambition technique.','cv.copy':'Un aperçu de ma formation, de mon expérience de recherche, de mes réalisations internationales et de mes intérêts techniques.','cv.download':'Télécharger le CV ↓','cv.edu':'FORMATION','cv.ensia':'ENSIA · Ingénierie de l’IA','cv.ensiaDesc':'5e année · Classée 1ère de la promotion pendant quatre années consécutives','cv.ehec':'EHEC · Commerce & Management','cv.ehecDesc':"Études de master en parallèle de l'ingénierie IA",'cv.research':'RECHERCHE','cv.craag':'CRAAG · Stage de recherche en IA','cv.craagDesc':'Centre de Recherche en Astronomie, Astrophysique et Géophysique','cv.academic':'ACADÉMIQUE','cv.bac':'Baccalauréat Mathématiques · 18,91/20','cv.bacDesc':'3e au niveau national',
'contact.eyebrow':'CONTACT','contact.title':'Construisons quelque chose de significatif.','contact.copy':'Ouverte aux collaborations de recherche, aux opportunités technologiques, aux stages, aux projets et aux échanges autour de l’intelligence artificielle et des technologies émergentes.',
'form.name':'Nom','form.email':'E-mail','form.subject':'Objet','form.message':'Message','form.send':'Envoyer le message ↗','footer.role':'Ingénieure IA · Chercheuse','project.visit':'Visiter le site ↗','project.gallery':'Galerie','project.replace':'Remplacez ces emplacements par vos vraies photos'
},
ar:{
'nav.about':'نبذة عني','nav.experience':'الخبرة والإنجازات','nav.projects':'المشاريع','nav.cv':'السيرة الذاتية','nav.contact':'تواصل معي','nav.download':'تحميل السيرة الذاتية',
'hero.role':'مهندسة ذكاء اصطناعي · باحثة · شغوفة بالتكنولوجيا','hero.copy':'طالبة هندسة ذكاء اصطناعي في ENSIA، تتمتع بمسار أكاديمي متميز وخبرة دولية في التكنولوجيا واهتمامات بحثية تشمل الذكاء الاصطناعي والتعلم المعزز والذكاء الاصطناعي الوكيلي وأنظمة 5G/6G.','hero.work':'استكشف أعمالي','hero.contact':'تواصل معي',
'stats.rank':'المرتبة الأولى في دفعة ENSIA لأربع سنوات متتالية','stats.bac':'بكالوريا الرياضيات · المرتبة الثالثة وطنيًا',
'about.title':'بناء أنظمة ذكية لحل مشكلات واقعية.','about.p1':'أنا طالبة في السنة الخامسة لهندسة الذكاء الاصطناعي في ENSIA، وأجمع بين الهندسة والبحث ودراسات التجارة والإدارة. وقد تشكل مساري الأكاديمي من خلال اهتمام قوي باتخاذ القرارات الذكية والتقنيات الناشئة.','about.p2':'تشمل اهتماماتي الذكاء الاصطناعي الوكيلي، والتعلم المعزز، واتخاذ القرار الهرمي، والشبكات الذكية، وتطبيقات الذكاء الاصطناعي في أنظمة 5G/6G، كما أستمتع بتحويل الأفكار التقنية إلى منتجات رقمية عملية.',
'experience.label':'الخبرة والإنجازات','experience.title':'محطات شكلت مسيرتي.',
'projects.eyebrow':'المشاريع','projects.title':'أعمال مختارة.','projects.subtitle':'ذكاء اصطناعي · بحث · برمجيات',
'ach.huawei.meta':'2026 · شنتشن، الصين','ach.huawei.title':'مسابقة Huawei ICT — الجائزة الكبرى العالمية','ach.huawei.card':'إنجاز في مسابقة دولية، مع التركيز على جانب الذكاء الاصطناعي من تحدٍ للتنبؤ بأعطال الحواسيب اعتمادًا على السلاسل الزمنية.',
'ach.seeds.meta':'تجربة دولية','ach.seeds.title':'Huawei Seeds for the Future','ach.seeds.card':'تمثيل الجزائر في شنتشن والتعرف على تقنيات Huawei و5G/6G والحوسبة السحابية والذكاء الاصطناعي والابتكار.',
'ach.craag.meta':'تجربة بحثية · الجزائر','ach.craag.title':'تدريب بحثي في الذكاء الاصطناعي — CRAAG','ach.craag.card':'تجربة بحثية في مركز البحث في علم الفلك والفيزياء الفلكية والجيوفيزياء.',
'ach.academic.meta':'التميز الأكاديمي','ach.academic.title':'التكريم الأكاديمي والوطني','ach.academic.card':'المرتبة الأولى في دفعة ENSIA لأربع سنوات، و18.91/20 في بكالوريا الرياضيات، والمرتبة الثالثة وطنيًا، وتكريم رئاسي وطني.',
'proj.sonatrach.title':'التنبؤ بالليثولوجيا لصالح سوناطراك','proj.sonatrach.card':'تطبيق التعلم الآلي على بيانات بترولية وجيولوجية للتنبؤ بالليثولوجيا.',
'proj.automotive.title':'منصة ذكاء اصطناعي لقطع غيار السيارات','proj.automotive.card':'مفهوم لمنصة ذكية متعددة اللغات تجمع بين البحث بالذكاء الاصطناعي وRAG والمخزون والموردين وأتمتة سير العمل.',
'proj.pfe.title':'دمج شبكات 5G مع الواقع المعزز','proj.pfe.card':'توجه أكاديمي حالي يستكشف دمج الاتصال من الجيل الجديد مع الواقع المعزز.',
'common.details':'عرض التفاصيل ←','common.explore':'استكشف المشروع ←',
'cv.eyebrow':'السيرة الذاتية','cv.title':'تميز أكاديمي.<br>طموح تقني.','cv.copy':'نبذة مختصرة عن تعليمي وخبرتي البحثية وإنجازاتي الدولية واهتماماتي التقنية.','cv.download':'تحميل السيرة الذاتية ↓','cv.edu':'التعليم','cv.ensia':'ENSIA · هندسة الذكاء الاصطناعي','cv.ensiaDesc':'السنة الخامسة · المرتبة الأولى في الدفعة لأربع سنوات متتالية','cv.ehec':'EHEC · التجارة والإدارة','cv.ehecDesc':'دراسات ماستر بالتوازي مع هندسة الذكاء الاصطناعي','cv.research':'البحث','cv.craag':'CRAAG · تدريب بحثي في الذكاء الاصطناعي','cv.craagDesc':'مركز البحث في علم الفلك والفيزياء الفلكية والجيوفيزياء','cv.academic':'أكاديمي','cv.bac':'بكالوريا الرياضيات · 18.91/20','cv.bacDesc':'المرتبة الثالثة وطنيًا',
'contact.eyebrow':'تواصل','contact.title':'لنبنِ شيئًا ذا قيمة.','contact.copy':'منفتحة على التعاونات البحثية والفرص التقنية والتدريبات والمشاريع والنقاشات الهادفة حول الذكاء الاصطناعي والتقنيات الناشئة.',
'form.name':'الاسم','form.email':'البريد الإلكتروني','form.subject':'الموضوع','form.message':'الرسالة','form.send':'إرسال الرسالة ↗','footer.role':'مهندسة ذكاء اصطناعي · باحثة','project.visit':'زيارة الموقع ↗','project.gallery':'معرض الصور','project.replace':'استبدل هذه المساحات بصورك الحقيقية'
},
de:{
'nav.about':'Über mich','nav.experience':'Erfahrung','nav.projects':'Projekte','nav.cv':'Lebenslauf','nav.contact':'Kontakt','nav.download':'Lebenslauf herunterladen',
'hero.role':'KI-Ingenieurin · Forscherin · Technologie-Enthusiastin','hero.copy':'KI-Engineering-Studentin an der ENSIA mit herausragender akademischer Leistung, internationaler Technologieerfahrung und Forschungsinteressen in Künstlicher Intelligenz, Reinforcement Learning, agentischer KI und 5G/6G-Systemen.','hero.work':'Meine Arbeit','hero.contact':'Kontakt aufnehmen',
'stats.rank':'Vier Jahre in Folge Platz 1 ihrer ENSIA-Kohorte','stats.bac':'Mathematik-Baccalauréat · landesweit Platz 3',
'about.title':'Intelligente Systeme für reale Probleme entwickeln.','about.p1':'Ich bin Studentin im fünften Jahr des KI-Engineerings an der ENSIA und verbinde Ingenieurwesen, Forschung und Managementstudien. Mein akademischer Weg ist von einem starken Interesse an intelligenter Entscheidungsfindung und neuen Technologien geprägt.','about.p2':'Meine Interessen umfassen agentische KI, Reinforcement Learning, hierarchische Entscheidungsfindung, intelligente Netzwerke und KI für 5G/6G. Außerdem entwickle ich gerne technische Ideen zu praktischen digitalen Produkten.',
'experience.label':'ERFAHRUNG & ERFOLGE','experience.title':'Meilensteine meines Weges.',
'projects.eyebrow':'PROJEKTE','projects.title':'Ausgewählte Arbeiten.','projects.subtitle':'KI · Forschung · Software',
'ach.huawei.meta':'2026 · SHENZHEN, CHINA','ach.huawei.title':'Huawei ICT Competition — Globaler Hauptpreis','ach.huawei.card':'Internationaler Wettbewerbserfolg mit Schwerpunkt auf dem KI-Teil einer Aufgabe zur Vorhersage von Computerausfällen anhand von Zeitreihen.',
'ach.seeds.meta':'INTERNATIONALE ERFAHRUNG','ach.seeds.title':'Huawei Seeds for the Future','ach.seeds.card':'Vertretung Algeriens in Shenzhen und Einblicke in Huawei-Technologien, 5G/6G, Cloud, KI und Innovation.',
'ach.craag.meta':'FORSCHUNGSERFAHRUNG · ALGERIEN','ach.craag.title':'KI-Forschungspraktikum — CRAAG','ach.craag.card':'Forschungserfahrung am Forschungszentrum für Astronomie, Astrophysik und Geophysik.',
'ach.academic.meta':'AKADEMISCHE EXZELLENZ','ach.academic.title':'Akademische und nationale Anerkennung','ach.academic.card':'Vier Jahre Platz 1 der ENSIA-Kohorte, 18,91/20 im Mathematik-Baccalauréat, landesweit Platz 3 und nationale Anerkennung auf Präsidentenebene.',
'proj.sonatrach.title':'Lithologie-Vorhersage für Sonatrach','proj.sonatrach.card':'Maschinelles Lernen auf Erdöl- und Geologiedaten zur Lithologie-Vorhersage.',
'proj.automotive.title':'KI-Plattform für Kfz-Ersatzteile','proj.automotive.card':'Konzept für eine intelligente mehrsprachige Plattform mit KI-Suche, RAG, Beständen, Lieferanten und Workflow-Automatisierung.',
'proj.pfe.title':'Integration von 5G mit Augmented Reality','proj.pfe.card':'Aktuelle akademische Richtung zur Verbindung der Konnektivität der nächsten Generation mit AR.',
'common.details':'Details ansehen →','common.explore':'Projekt ansehen →',
'cv.eyebrow':'LEBENSLAUF','cv.title':'Akademische Exzellenz.<br>Technischer Anspruch.','cv.copy':'Ein kompakter Überblick über Ausbildung, Forschungserfahrung, internationale Erfolge und technische Interessen.','cv.download':'Lebenslauf herunterladen ↓','cv.edu':'AUSBILDUNG','cv.ensia':'ENSIA · KI-Engineering','cv.ensiaDesc':'5. Jahr · Vier Jahre in Folge Platz 1 der Kohorte','cv.ehec':'EHEC · Commerce & Management','cv.ehecDesc':'Masterstudium parallel zum KI-Engineering','cv.research':'FORSCHUNG','cv.craag':'CRAAG · KI-Forschungspraktikum','cv.craagDesc':'Forschungszentrum für Astronomie, Astrophysik und Geophysik','cv.academic':'AKADEMISCH','cv.bac':'Mathematik-Baccalauréat · 18,91/20','cv.bacDesc':'Landesweit Platz 3',
'contact.eyebrow':'KONTAKT','contact.title':'Lass uns etwas Bedeutungsvolles schaffen.','contact.copy':'Offen für Forschungskooperationen, technologische Chancen, Praktika, Projekte und Gespräche über Künstliche Intelligenz und neue Technologien.',
'form.name':'Name','form.email':'E-Mail','form.subject':'Betreff','form.message':'Nachricht','form.send':'Nachricht senden ↗','footer.role':'KI-Ingenieurin · Forscherin','project.visit':'Website besuchen ↗','project.gallery':'Galerie','project.replace':'Ersetze diese Platzhalter durch deine echten Fotos'
},
es:{
'nav.about':'Sobre mí','nav.experience':'Experiencia','nav.projects':'Proyectos','nav.cv':'CV','nav.contact':'Contacto','nav.download':'Descargar CV',
'hero.role':'Ingeniera de IA · Investigadora · Entusiasta de la tecnología','hero.copy':'Estudiante de Ingeniería de IA en ENSIA, con un sólido expediente académico, experiencia tecnológica internacional e intereses de investigación en Inteligencia Artificial, Reinforcement Learning, IA agéntica y sistemas 5G/6G.','hero.work':'Ver mi trabajo','hero.contact':'Contactar',
'stats.rank':'1ª de su promoción en ENSIA durante cuatro años consecutivos','stats.bac':'Bachillerato de Matemáticas · 3ª a nivel nacional',
'about.title':'Construyendo sistemas inteligentes para problemas reales.','about.p1':'Soy estudiante de quinto año de Ingeniería de IA en ENSIA y combino ingeniería, investigación y estudios de gestión. Mi trayectoria académica está marcada por un gran interés en la toma de decisiones inteligentes y las tecnologías emergentes.','about.p2':'Mis intereses incluyen IA agéntica, aprendizaje por refuerzo, toma de decisiones jerárquica, redes inteligentes y sistemas 5G/6G impulsados por IA. También disfruto convirtiendo ideas técnicas en productos digitales prácticos.',
'experience.label':'EXPERIENCIA Y LOGROS','experience.title':'Hitos que han marcado mi trayectoria.',
'projects.eyebrow':'PROYECTOS','projects.title':'Trabajos seleccionados.','projects.subtitle':'IA · Investigación · Software',
'ach.huawei.meta':'2026 · SHENZHEN, CHINA','ach.huawei.title':'Huawei ICT Competition — Gran Premio Mundial','ach.huawei.card':'Logro en una competición internacional, centrado en la parte de IA de un reto de predicción de fallos informáticos mediante series temporales.',
'ach.seeds.meta':'EXPERIENCIA INTERNACIONAL','ach.seeds.title':'Huawei Seeds for the Future','ach.seeds.card':'Representación de Argelia en Shenzhen y exploración de tecnologías Huawei, 5G/6G, cloud, IA e innovación.',
'ach.craag.meta':'EXPERIENCIA DE INVESTIGACIÓN · ARGELIA','ach.craag.title':'Prácticas de investigación en IA — CRAAG','ach.craag.card':'Experiencia de investigación en el Centro de Investigación de Astronomía, Astrofísica y Geofísica.',
'ach.academic.meta':'EXCELENCIA ACADÉMICA','ach.academic.title':'Reconocimiento académico y nacional','ach.academic.card':'1.ª de la promoción en ENSIA durante cuatro años, 18,91/20 en Bachillerato de Matemáticas, 3.ª a nivel nacional y reconocimiento presidencial nacional.',
'proj.sonatrach.title':'Predicción de litología para Sonatrach','proj.sonatrach.card':'Aplicación de aprendizaje automático a datos petroleros y geológicos para predecir la litología.',
'proj.automotive.title':'Plataforma de IA para repuestos de automoción','proj.automotive.card':'Concepto de plataforma multilingüe inteligente que combina búsqueda con IA, RAG, stock, proveedores y automatización de flujos.',
'proj.pfe.title':'Integración de 5G con Realidad Aumentada','proj.pfe.card':'Línea académica actual que explora la integración de conectividad de nueva generación con RA.',
'common.details':'Ver detalles →','common.explore':'Explorar proyecto →',
'cv.eyebrow':'CV','cv.title':'Excelencia académica.<br>Ambición técnica.','cv.copy':'Un resumen de mi formación, experiencia de investigación, logros internacionales e intereses técnicos.','cv.download':'Descargar CV ↓','cv.edu':'EDUCACIÓN','cv.ensia':'ENSIA · Ingeniería de IA','cv.ensiaDesc':'5.º año · 1.ª de la promoción durante cuatro años consecutivos','cv.ehec':'EHEC · Comercio y Gestión','cv.ehecDesc':'Estudios de máster junto con Ingeniería de IA','cv.research':'INVESTIGACIÓN','cv.craag':'CRAAG · Prácticas de investigación en IA','cv.craagDesc':'Centro de Investigación de Astronomía, Astrofísica y Geofísica','cv.academic':'ACADÉMICO','cv.bac':'Bachillerato de Matemáticas · 18,91/20','cv.bacDesc':'3.ª a nivel nacional',
'contact.eyebrow':'CONTACTO','contact.title':'Construyamos algo significativo.','contact.copy':'Abierta a colaboraciones de investigación, oportunidades tecnológicas, prácticas, proyectos y conversaciones sobre Inteligencia Artificial y tecnologías emergentes.',
'form.name':'Nombre','form.email':'Correo electrónico','form.subject':'Asunto','form.message':'Mensaje','form.send':'Enviar mensaje ↗','footer.role':'Ingeniera de IA · Investigadora','project.visit':'Visitar sitio web ↗','project.gallery':'Galería','project.replace':'Sustituye estos espacios por tus fotos reales'
}
};
function applyLang(lang){
 document.documentElement.lang=lang;
 document.documentElement.dir=lang==="ar"?"rtl":"ltr";
 document.body.classList.toggle("rtl",lang==="ar");
 document.querySelectorAll("[data-i18n]").forEach(el=>{
   const k=el.dataset.i18n;
   if(T[lang]?.[k]!==undefined) el.innerHTML=T[lang][k];
 });
 document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>{
   const k=el.dataset.i18nPlaceholder;
   if(T[lang]?.[k]!==undefined) el.placeholder=T[lang][k];
 });
 localStorage.setItem("lang",lang);
}
const lang=localStorage.getItem("lang")||"en";document.getElementById("language").value=lang;applyLang(lang);document.getElementById("language").addEventListener("change",e=>{applyLang(e.target.value); const modal=document.getElementById("modal"); if(modal.classList.contains("open")){ const key=window.currentDetailKey; if(key) openDetail(key); }});

// Theme selector: persists across visits.
(function(){const root=document.documentElement,light=document.getElementById("themeLight"),dark=document.getElementById("themeDark");function setTheme(t){root.setAttribute("data-theme",t);light.classList.toggle("active",t==="light");dark.classList.toggle("active",t==="dark");localStorage.setItem("theme",t)}const saved=localStorage.getItem("theme")||"light";setTheme(saved);light.addEventListener("click",()=>setTheme("light"));dark.addEventListener("click",()=>setTheme("dark"))})();
